export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',
  FRONTEND_URL = 'FRONTEND_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  REFRESH_TOKEN_LENGTH = 'REFRESH_TOKEN_LENGTH',
  REFRESH_TOKEN_EXPIRES_DAYS = 'REFRESH_TOKEN_EXPIRES_DAYS',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_PASS = 'ADMIN_PASS',

  DISTRIBUTOR_EMAIL = 'DISTRIBUTOR_EMAIL',
  DISTRIBUTOR_PASS = 'DISTRIBUTOR_PASS',

  ACCOUNTANT_EMAIL = 'ACCOUNTANT_EMAIL',
  ACCOUNTANT_PASS = 'ACCOUNTANT_PASS',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_MEDIACONVERT_ENDPOINT = 'AWS_MEDIACONVERT_ENDPOINT',
  AWS_MEDIACONVERT_ROLE_ARN = 'AWS_MEDIACONVERT_ROLE_ARN',
}
